### ISSUE TITLE
Popup - How Does One Select

### ISSUE THREAD

**Issue by DanteAyagawe** [HolographicWings/LethalExpansion#9]
A popup shows up requesting for an update, I cannot select any of the options.

**Comment by DanteAyagawe** [comment]
also after update, it still shows it is not updated... weird

**Comment by HolographicWings** [comment]
> also after update, it still shows it is not updated... weird

Yes sorry i forgot to change the version number in the update x) it's fixed now
And next time the popup have an issue, can you show me in video please ?

**Comment by DanteAyagawe** [comment]
I can't seem to replicate the bug anymore, however you forgot the version number again to 1.2.4, mine still shows 1.2.3
![Untitled](https://github.com/HolographicWings/LethalExpansion/assets/72873254/3aed6f07-eaa8-43d6-af27-94c053ce312d)

**Comment by DanteAyagawe** [comment]
Also the bug if I can picture it to you, imagine being in the game, but the popup for the update shows in game, pressing tab hides the popup, and going to chat mode doesn't show the cursor in game.

So I am unable to select ignore or update, but it fixed itself so it's fine

**Comment by HolographicWings** [comment]
> Also the bug if I can picture it to you, imagine being in the game, but the popup for the update shows in game, pressing tab hides the popup, and going to chat mode doesn't show the cursor in game.
> 
> So I am unable to select ignore or update, but it fixed itself so it's fine

The popup is not supposed to show in game

And i forgot again to change the version in the mod, so it tell out to date >_>..

**Comment by DanteAyagawe** [comment]
Your gud m8

**Comment by HolographicWings** [comment]
@DanteAyagawe send me logs if the popup show again elsewhere than the main menu

**Comment by HolographicWings** [comment]
let me know if fixed @DanteAyagawe
